# Generated by Django 4.2.6 on 2023-11-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gazebo', '0002_alter_course_days_alter_course_end_time_and_more'),
        ('gazebo', '0002_alter_course_days_alter_course_is_open'),
    ]

    operations = [
    ]
