# Generated by Django 4.2.6 on 2023-12-05 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gazebo', '0003_merge_20231126_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='watch',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='student_id',
        ),
        migrations.AddField(
            model_name='watch',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gazebo.course'),
        ),
        migrations.AddField(
            model_name='watch',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
