# Generated by Django 4.2.5 on 2023-10-23 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazebo', '0003_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('course_id', models.CharField(max_length=10)),
                ('num_students', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(default='M W F', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='is_open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='num_watches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
